from dataclasses import dataclass


@dataclass(frozen=True)
class City:
    plate_code: int
    name: str
    slug: str
    region: str


CITIES = [
    City(1, "Adana", "adana", "mediterranean"),
    City(2, "Adiyaman", "adiyaman", "southeastern_anatolia"),
    City(3, "Afyonkarahisar", "afyonkarahisar", "aegean"),
    City(4, "Agri", "agri", "eastern_anatolia"),
    City(5, "Amasya", "amasya", "black_sea"),
    City(6, "Ankara", "ankara", "central_anatolia"),
    City(7, "Antalya", "antalya", "mediterranean"),
    City(8, "Artvin", "artvin", "black_sea"),
    City(9, "Aydin", "aydin", "aegean"),
    City(10, "Balikesir", "balikesir", "marmara"),
    City(11, "Bilecik", "bilecik", "marmara"),
    City(12, "Bingol", "bingol", "eastern_anatolia"),
    City(13, "Bitlis", "bitlis", "eastern_anatolia"),
    City(14, "Bolu", "bolu", "black_sea"),
    City(15, "Burdur", "burdur", "mediterranean"),
    City(16, "Bursa", "bursa", "marmara"),
    City(17, "Canakkale", "canakkale", "marmara"),
    City(18, "Cankiri", "cankiri", "central_anatolia"),
    City(19, "Corum", "corum", "black_sea"),
    City(20, "Denizli", "denizli", "aegean"),
    City(21, "Diyarbakir", "diyarbakir", "southeastern_anatolia"),
    City(22, "Edirne", "edirne", "marmara"),
    City(23, "Elazig", "elazig", "eastern_anatolia"),
    City(24, "Erzincan", "erzincan", "eastern_anatolia"),
    City(25, "Erzurum", "erzurum", "eastern_anatolia"),
    City(26, "Eskisehir", "eskisehir", "central_anatolia"),
    City(27, "Gaziantep", "gaziantep", "southeastern_anatolia"),
    City(28, "Giresun", "giresun", "black_sea"),
    City(29, "Gumushane", "gumushane", "black_sea"),
    City(30, "Hakkari", "hakkari", "southeastern_anatolia"),
    City(31, "Hatay", "hatay", "mediterranean"),
    City(32, "Isparta", "isparta", "mediterranean"),
    City(33, "Mersin", "mersin", "mediterranean"),
    City(34, "Istanbul", "istanbul", "marmara"),
    City(35, "Izmir", "izmir", "aegean"),
    City(36, "Kars", "kars", "eastern_anatolia"),
    City(37, "Kastamonu", "kastamonu", "black_sea"),
    City(38, "Kayseri", "kayseri", "central_anatolia"),
    City(39, "Kirklareli", "kirklareli", "marmara"),
    City(40, "Kirsehir", "kirsehir", "central_anatolia"),
    City(41, "Kocaeli", "kocaeli", "marmara"),
    City(42, "Konya", "konya", "central_anatolia"),
    City(43, "Kutahya", "kutahya", "aegean"),
    City(44, "Malatya", "malatya", "eastern_anatolia"),
    City(45, "Manisa", "manisa", "aegean"),
    City(46, "Kahramanmaras", "kahramanmaras", "mediterranean"),
    City(47, "Mardin", "mardin", "southeastern_anatolia"),
    City(48, "Mugla", "mugla", "aegean"),
    City(49, "Mus", "mus", "eastern_anatolia"),
    City(50, "Nevsehir", "nevsehir", "central_anatolia"),
    City(51, "Nigde", "nigde", "central_anatolia"),
    City(52, "Ordu", "ordu", "black_sea"),
    City(53, "Rize", "rize", "black_sea"),
    City(54, "Sakarya", "sakarya", "marmara"),
    City(55, "Samsun", "samsun", "black_sea"),
    City(56, "Siirt", "siirt", "southeastern_anatolia"),
    City(57, "Sinop", "sinop", "black_sea"),
    City(58, "Sivas", "sivas", "central_anatolia"),
    City(59, "Tekirdag", "tekirdag", "marmara"),
    City(60, "Tokat", "tokat", "black_sea"),
    City(61, "Trabzon", "trabzon", "black_sea"),
    City(62, "Tunceli", "tunceli", "eastern_anatolia"),
    City(63, "Sanliurfa", "sanliurfa", "southeastern_anatolia"),
    City(64, "Usak", "usak", "aegean"),
    City(65, "Van", "van", "eastern_anatolia"),
    City(66, "Yozgat", "yozgat", "central_anatolia"),
    City(67, "Zonguldak", "zonguldak", "black_sea"),
    City(68, "Aksaray", "aksaray", "central_anatolia"),
    City(69, "Bayburt", "bayburt", "black_sea"),
    City(70, "Karaman", "karaman", "central_anatolia"),
    City(71, "Kirikkale", "kirikkale", "central_anatolia"),
    City(72, "Batman", "batman", "southeastern_anatolia"),
    City(73, "Sirnak", "sirnak", "southeastern_anatolia"),
    City(74, "Bartin", "bartin", "black_sea"),
    City(75, "Ardahan", "ardahan", "eastern_anatolia"),
    City(76, "Igdir", "igdir", "eastern_anatolia"),
    City(77, "Yalova", "yalova", "marmara"),
    City(78, "Karabuk", "karabuk", "black_sea"),
    City(79, "Kilis", "kilis", "southeastern_anatolia"),
    City(80, "Osmaniye", "osmaniye", "mediterranean"),
    City(81, "Duzce", "duzce", "black_sea"),
]


CITY_BY_SLUG = {city.slug: city for city in CITIES}
