from dataclasses import dataclass
from typing import List

from .cities import CITIES, CITY_BY_SLUG, City


@dataclass(frozen=True)
class LocalMarketCandidate:
    city_slug: str
    market_name: str
    market_slug: str
    market_scope: str
    entrypoint_url: str
    evidence_url: str
    verification_status: str
    source_type: str
    notes: str


@dataclass(frozen=True)
class CityDiscoveryTask:
    city_plate_code: int
    status: str
    priority_score: int
    notes: str


@dataclass(frozen=True)
class CityDiscoveryQuery:
    city_plate_code: int
    query_text: str
    query_kind: str
    priority_score: int


@dataclass(frozen=True)
class CityCoverageStatus:
    city_plate_code: int
    coverage_status: str
    verified_market_count: int
    notes: str


def build_city_discovery_tasks() -> List[CityDiscoveryTask]:
    metro_priority = {"istanbul", "ankara", "izmir", "antalya", "adana", "gaziantep", "bursa", "kocaeli", "konya"}
    tasks: List[CityDiscoveryTask] = []
    for city in CITIES:
        priority = 100 if city.slug in metro_priority else 80
        tasks.append(
            CityDiscoveryTask(
                city_plate_code=city.plate_code,
                status="pending",
                priority_score=priority,
                notes=f"{city.name} icin yerel online market taramasi gerekli",
            )
        )
    return tasks


def build_city_discovery_queries() -> List[CityDiscoveryQuery]:
    metro_priority = {"istanbul", "ankara", "izmir", "antalya", "adana", "gaziantep", "bursa", "kocaeli", "konya"}
    query_templates = [
        ("official_online_market", "{city} online market"),
        ("official_sanal_market", "{city} sanal market"),
        ("local_delivery_market", "{city} yerel market online alisveris"),
        ("delivery_zone_market", "{city} kapiya teslim market"),
    ]
    queries: List[CityDiscoveryQuery] = []
    for city in CITIES:
        base_priority = 100 if city.slug in metro_priority else 80
        for query_kind, template in query_templates:
            queries.append(
                CityDiscoveryQuery(
                    city_plate_code=city.plate_code,
                    query_text=template.format(city=city.name),
                    query_kind=query_kind,
                    priority_score=base_priority,
                )
            )
    return queries


def build_city_coverage_statuses() -> List[CityCoverageStatus]:
    verified_counts = {}
    for candidate in VERIFIED_LOCAL_MARKET_CANDIDATES:
        verified_counts[candidate.city_slug] = verified_counts.get(candidate.city_slug, 0) + 1

    statuses: List[CityCoverageStatus] = []
    for city in CITIES:
        market_count = verified_counts.get(city.slug, 0)
        if market_count:
            statuses.append(
                CityCoverageStatus(
                    city_plate_code=city.plate_code,
                    coverage_status="verified_local_sources",
                    verified_market_count=market_count,
                    notes=f"{city.name} icin {market_count} yerel online market kaynagi dogrulandi",
                )
            )
        else:
            statuses.append(
                CityCoverageStatus(
                    city_plate_code=city.plate_code,
                    coverage_status="discovery_pending",
                    verified_market_count=0,
                    notes=f"{city.name} icin yerel online market dogrulamasi suruyor",
                )
            )
    return statuses


VERIFIED_LOCAL_MARKET_CANDIDATES: List[LocalMarketCandidate] = [
    LocalMarketCandidate(
        city_slug="konya",
        market_name="Mismar Online",
        market_slug="mismar-konya",
        market_scope="city_specific",
        entrypoint_url="https://www.mismarsanalmarket.com/",
        evidence_url="https://www.mismarsanalmarket.com/",
        verification_status="verified",
        source_type="repo_and_live_site",
        notes="Repo already contains Konya-focused scraper code and live storefront.",
    ),
    LocalMarketCandidate(
        city_slug="konya",
        market_name="Celikkayalar Market",
        market_slug="celikkayalar-konya",
        market_scope="city_specific",
        entrypoint_url="https://celikkayalaronline.com/",
        evidence_url="https://celikkayalaronline.com/",
        verification_status="verified",
        source_type="official_site_and_app_link",
        notes="Official Konya online market landing page is public and routes category/product URLs on the same domain, but current web surface redirects every catalog path to the landing/app-download experience; onboarding should continue with a mobile app session flow.",
    ),
    LocalMarketCandidate(
        city_slug="ankara",
        market_name="Yunus Market Online",
        market_slug="yunus-market-ankara",
        market_scope="city_specific",
        entrypoint_url="https://www.yunusonline.com/",
        evidence_url="https://www.yunusonline.com/",
        verification_status="verified",
        source_type="repo_and_live_site",
        notes="Repo already contains Ankara-focused Yunus Market reference.",
    ),
    LocalMarketCandidate(
        city_slug="kayseri",
        market_name="Sehzade Online",
        market_slug="sehzade-kayseri",
        market_scope="city_specific",
        entrypoint_url="https://sehzadeonline.com/",
        evidence_url="https://sehzadeonline.com/",
        verification_status="verified",
        source_type="repo_and_live_site",
        notes="Repo already contains Kayseri-focused Sehzade reference.",
    ),
    LocalMarketCandidate(
        city_slug="izmir",
        market_name="IZMAR",
        market_slug="izmar-izmir",
        market_scope="city_specific",
        entrypoint_url="https://www.izmar.info/home",
        evidence_url="https://www.izmar.info/home",
        verification_status="verified",
        source_type="official_site",
        notes="Official Izmir city market storefront with public price pages.",
    ),
    LocalMarketCandidate(
        city_slug="izmir",
        market_name="Kuzey Market",
        market_slug="kuzey-market-izmir",
        market_scope="district_or_city_specific",
        entrypoint_url="https://kuzeymarket.com.tr/",
        evidence_url="https://kuzeymarket.com.tr/",
        verification_status="verified",
        source_type="official_site",
        notes="Online siparis flow and Izmir address visible on site.",
    ),
    LocalMarketCandidate(
        city_slug="izmir",
        market_name="Basdas Online Market",
        market_slug="basdas-online-izmir",
        market_scope="city_specific",
        entrypoint_url="https://basdasonline.com/",
        evidence_url="https://basdasonline.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official online storefront lists Gaziemir / Izmir contact and grocery catalog.",
    ),
    LocalMarketCandidate(
        city_slug="izmir",
        market_name="Baris Gross Market",
        market_slug="baris-gross-izmir",
        market_scope="city_specific",
        entrypoint_url="https://barisgrossonlinemagaza.com/",
        evidence_url="https://barisgrossonlinemagaza.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official SPA storefront titled Baris Gross Market is reachable on the public domain and can be promoted as an Izmir alternative while API discovery continues.",
    ),
    LocalMarketCandidate(
        city_slug="istanbul",
        market_name="Yalla Market",
        market_slug="yalla-market-istanbul",
        market_scope="district_cluster",
        entrypoint_url="https://yallamarket.com.tr/",
        evidence_url="https://yallamarket.com.tr/",
        verification_status="verified",
        source_type="official_site",
        notes="Official site states Istanbul availability and served districts.",
    ),
    LocalMarketCandidate(
        city_slug="istanbul",
        market_name="Showmar Hipermarketleri",
        market_slug="showmar-istanbul",
        market_scope="district_cluster",
        entrypoint_url="https://www.showmar.com.tr/",
        evidence_url="https://www.showmar.com.tr/iletisim",
        verification_status="verified",
        source_type="official_site",
        notes="Official online market site lists Istanbul / Atasehir contact and live grocery catalog.",
    ),
    LocalMarketCandidate(
        city_slug="antalya",
        market_name="Saladdo",
        market_slug="saladdo-antalya",
        market_scope="city_specific",
        entrypoint_url="https://www.saladdo.com/",
        evidence_url="https://www.saladdo.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official site states Antalya delivery coverage.",
    ),
    LocalMarketCandidate(
        city_slug="gaziantep",
        market_name="Nokta Jet",
        market_slug="nokta-jet-gaziantep",
        market_scope="city_specific",
        entrypoint_url="https://www.noktajet.com/",
        evidence_url="https://www.noktajet.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Gaziantep market storefront with grocery catalog.",
    ),
    LocalMarketCandidate(
        city_slug="gaziantep",
        market_name="Gaziantep Gross Market",
        market_slug="gaziantep-gross-market",
        market_scope="city_specific",
        entrypoint_url="https://www.gaziantepgross.com/",
        evidence_url="https://www.gaziantepgross.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official online market storefront for Gaziantep.",
    ),
    LocalMarketCandidate(
        city_slug="adana",
        market_name="Groseri",
        market_slug="groseri-adana",
        market_scope="city_specific",
        entrypoint_url="https://www.groseri.com.tr/",
        evidence_url="https://www.groseri.com.tr/",
        verification_status="verified",
        source_type="official_site",
        notes="Official online market storefront requires il / ilce / mahalle selection before shopping.",
    ),
    LocalMarketCandidate(
        city_slug="adiyaman",
        market_name="Kahta Online Market",
        market_slug="kahta-online-market-adiyaman",
        market_scope="city_specific",
        entrypoint_url="https://kahtaonlinemarket.com/",
        evidence_url="https://apkpure.com/kahta-online-market/tr.com.akinsoft.kahtaonlinemarket",
        verification_status="verified",
        source_type="official_site_plus_app_listing",
        notes="The official app listing states it is the mobile application of kahtaonlinemarket.com for Adiyaman / Kahta.",
    ),
    LocalMarketCandidate(
        city_slug="afyonkarahisar",
        market_name="Soz Sanal Market",
        market_slug="soz-sanal-market-afyon",
        market_scope="city_specific",
        entrypoint_url="https://www.afyonsoz.com/",
        evidence_url="https://www.afyonsoz.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Afyonkarahisar local market site advertises same-day delivery and online ordering.",
    ),
    LocalMarketCandidate(
        city_slug="mersin",
        market_name="Groseri",
        market_slug="groseri-mersin",
        market_scope="city_specific",
        entrypoint_url="https://www.groseri.com.tr/",
        evidence_url="https://www.groseri.com.tr/",
        verification_status="verified",
        source_type="official_site_plus_regional_evidence",
        notes="Official online storefront supports city selection; public regional coverage references Adana and Mersin operations.",
    ),
    LocalMarketCandidate(
        city_slug="bursa",
        market_name="Ozhan Market",
        market_slug="ozhan-bursa",
        market_scope="city_specific",
        entrypoint_url="https://www.ozhan.com.tr/",
        evidence_url="https://www.ozhan.com.tr/en/haberler/ozhan-da-online-alisveris-tam-gaz",
        verification_status="verified",
        source_type="official_site",
        notes="Official Bursa chain states online shopping and mobile ordering through ozhan.com.tr.",
    ),
    LocalMarketCandidate(
        city_slug="balikesir",
        market_name="Balikesir Sanal Market",
        market_slug="balikesir-sanal-market",
        market_scope="city_specific",
        entrypoint_url="https://balikesirsanalmarket.com/",
        evidence_url="https://balikesirsanalmarket.com/iletisim/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Balikesir local market storefront exposes grocery categories and local contact details.",
    ),
    LocalMarketCandidate(
        city_slug="batman",
        market_name="Batman Sanal Market",
        market_slug="batman-sanal-market",
        market_scope="city_specific",
        entrypoint_url="https://batmansanalmarket.com/",
        evidence_url="https://batmansanalmarket.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Batman local online market storefront advertises same-day delivery and grocery ordering.",
    ),
    LocalMarketCandidate(
        city_slug="aksaray",
        market_name="Depoo Sanal Market",
        market_slug="depoo-aksaray",
        market_scope="city_specific",
        entrypoint_url="https://play.google.com/store/apps/details?hl=tr&id=com.sanaldepoo.depoo",
        evidence_url="https://play.google.com/store/apps/details?hl=tr&id=com.sanaldepoo.depoo",
        verification_status="verified",
        source_type="official_app_listing",
        notes="Official Google Play listing states the service currently operates only in Aksaray.",
    ),
    LocalMarketCandidate(
        city_slug="bolu",
        market_name="Biistek Sanal Market",
        market_slug="biistek-bolu",
        market_scope="city_specific",
        entrypoint_url="https://biistek.com/",
        evidence_url="https://bolu.genckobi.com/firma/biistek-sanal-market/iletisim",
        verification_status="verified",
        source_type="official_site_plus_directory_evidence",
        notes="Bolu directory entry links the live shopping site and local address for Biistek Sanal Market.",
    ),
    LocalMarketCandidate(
        city_slug="canakkale",
        market_name="delVita",
        market_slug="delvita-canakkale",
        market_scope="city_specific",
        entrypoint_url="https://delvita.com.tr/",
        evidence_url="https://delvita.com.tr/iletisim/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Canakkale local market storefront lists branches and online grocery ordering.",
    ),
    LocalMarketCandidate(
        city_slug="denizli",
        market_name="Alp Supermarket",
        market_slug="alp-supermarket-denizli",
        market_scope="city_specific",
        entrypoint_url="https://www.alpsupermarket.com/",
        evidence_url="https://www.alpsupermarket.com/kurumsal",
        verification_status="verified",
        source_type="official_site",
        notes="Official Denizli local market site includes online ordering and corporate branch information.",
    ),
    LocalMarketCandidate(
        city_slug="diyarbakir",
        market_name="Carmar Sanal Market",
        market_slug="carmar-diyarbakir",
        market_scope="city_specific",
        entrypoint_url="https://www.carmar.com.tr/",
        evidence_url="https://www.carmar.com.tr/iletisim",
        verification_status="verified",
        source_type="official_site",
        notes="Official Diyarbakir local market site lists Kayapinar / Diyarbakir contact details and online ordering.",
    ),
    LocalMarketCandidate(
        city_slug="edirne",
        market_name="Margi Market",
        market_slug="margi-edirne",
        market_scope="city_specific",
        entrypoint_url="https://margi.com.tr/",
        evidence_url="https://www.margi.com.tr/%C4%B0leti%C5%9Fim---%C5%9Eubeler.html",
        verification_status="verified",
        source_type="official_site",
        notes="Official Edirne local market site lists branches and direct online market ordering.",
    ),
    LocalMarketCandidate(
        city_slug="duzce",
        market_name="Duzpas",
        market_slug="duzpas-duzce",
        market_scope="city_specific",
        entrypoint_url="https://www.duzpas.com/",
        evidence_url="https://www.duzpas.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Duzce local market site advertises online ordering and city-focused delivery flow.",
    ),
    LocalMarketCandidate(
        city_slug="eskisehir",
        market_name="Eskisehir Market",
        market_slug="eskisehir-market",
        market_scope="city_specific",
        entrypoint_url="https://eskisehirmarket.com/",
        evidence_url="https://eskisehirmarket.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Eskişehir storefront includes local contact information and online ordering flow.",
    ),
    LocalMarketCandidate(
        city_slug="giresun",
        market_name="Ankamar",
        market_slug="ankamar-giresun",
        market_scope="city_specific",
        entrypoint_url="https://www.ankamar.net/",
        evidence_url="https://ankamar.net/magazadetay/bulancak-magazasi",
        verification_status="verified",
        source_type="official_site",
        notes="Official regional market site lists Giresun Bulancak branch and online storefront support.",
    ),
    LocalMarketCandidate(
        city_slug="giresun",
        market_name="Afta Market",
        market_slug="afta-market-giresun",
        market_scope="city_specific",
        entrypoint_url="https://www.aftamarket.com.tr/",
        evidence_url="https://www.aftamarket.com.tr/giresun",
        verification_status="verified",
        source_type="official_site",
        notes="Official local chain site lists Giresun service pages and city-based online ordering.",
    ),
    LocalMarketCandidate(
        city_slug="kocaeli",
        market_name="Taso Market",
        market_slug="taso-market-kocaeli",
        market_scope="city_specific",
        entrypoint_url="https://www.tasomarket.com/",
        evidence_url="https://www.tasomarket.com/hakkimizda",
        verification_status="verified",
        source_type="official_site",
        notes="Official Kocaeli market chain with live catalog, same-day delivery and branch information.",
    ),
    LocalMarketCandidate(
        city_slug="karaman",
        market_name="Sele",
        market_slug="sele-karaman",
        market_scope="city_specific",
        entrypoint_url="https://apkpure.com/sele/io.com.sele",
        evidence_url="https://apkpure.com/sele/io.com.sele",
        verification_status="verified",
        source_type="official_app_listing",
        notes="Official app listing states the market and restaurant ordering service operates within Karaman province.",
    ),
    LocalMarketCandidate(
        city_slug="isparta",
        market_name="IYAS",
        market_slug="iyas-isparta",
        market_scope="city_specific",
        entrypoint_url="https://www.iyas.com.tr/",
        evidence_url="https://www.iyas.com.tr/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Isparta chain site includes sanal market navigation and online ordering entry points.",
    ),
    LocalMarketCandidate(
        city_slug="hatay",
        market_name="Hat1",
        market_slug="hat1-hatay",
        market_scope="city_specific",
        entrypoint_url="https://www.hat1.com.tr/",
        evidence_url="https://www.hat1.com.tr/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Hatay local market site exposes online ordering and city-focused grocery delivery messaging.",
    ),
    LocalMarketCandidate(
        city_slug="erzincan",
        market_name="AVEME",
        market_slug="aveme-erzincan",
        market_scope="city_specific",
        entrypoint_url="https://www.aveme.com.tr/",
        evidence_url="https://www.aveme.com.tr/index.php?route=information%2Fcontact",
        verification_status="verified",
        source_type="official_site",
        notes="Official Erzincan online market storefront exposes local contact details and grocery catalog.",
    ),
    LocalMarketCandidate(
        city_slug="erzincan",
        market_name="Ayaydin Gross Market",
        market_slug="ayaydin-gross-erzincan",
        market_scope="city_specific",
        entrypoint_url="https://ayaydingrossmarket.com/",
        evidence_url="https://ayaydingrossmarket.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Erzincan gross market storefront provides direct online shopping access.",
    ),
    LocalMarketCandidate(
        city_slug="erzurum",
        market_name="Guvendik Hipermarketcilik",
        market_slug="guvendik-erzurum",
        market_scope="city_specific",
        entrypoint_url="https://www.guvendikmarket.com/",
        evidence_url="https://www.guvendikmarket.com/shop/",
        verification_status="verified",
        source_type="official_site_plus_app_listing",
        notes="Official Erzurum storefront exposes product catalog, Yakutiye address details and mobile app links on the same domain.",
    ),
    LocalMarketCandidate(
        city_slug="elazig",
        market_name="Isik Market",
        market_slug="isik-market-elazig",
        market_scope="city_specific",
        entrypoint_url="https://www.isikmarket.com.tr/",
        evidence_url="https://www.isikmarket.com.tr/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Elazig online market storefront includes local branches and web ordering.",
    ),
    LocalMarketCandidate(
        city_slug="samsun",
        market_name="Samsun Market",
        market_slug="samsun-market",
        market_scope="city_specific",
        entrypoint_url="https://www.samsunmarket.com/",
        evidence_url="https://www.samsunmarket.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Samsun online market storefront advertises web and app ordering with local delivery.",
    ),
    LocalMarketCandidate(
        city_slug="ordu",
        market_name="Kalafatlar Market",
        market_slug="kalafatlar-ordu",
        market_scope="city_specific",
        entrypoint_url="https://kalafatlar.com/",
        evidence_url="https://kalafatlar.com/hakkimizda",
        verification_status="verified",
        source_type="official_site",
        notes="Official Ordu local market site exposes online ordering and branch information.",
    ),
    LocalMarketCandidate(
        city_slug="ordu",
        market_name="Gelsineve",
        market_slug="gelsineve-ordu",
        market_scope="city_specific",
        entrypoint_url="https://www.gelsineve.com/",
        evidence_url="https://www.gelsineve.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Ordu online market storefront shows Altinordu / Ordu contact and same-city delivery messaging.",
    ),
    LocalMarketCandidate(
        city_slug="ordu",
        market_name="Ankamar",
        market_slug="ankamar-ordu",
        market_scope="city_specific",
        entrypoint_url="https://www.ankamar.net/",
        evidence_url="https://ankamar.net/vizyonumuz",
        verification_status="verified",
        source_type="official_site",
        notes="Official regional market site states online shopping support for Ordu and Giresun operations.",
    ),
    LocalMarketCandidate(
        city_slug="malatya",
        market_name="Ozkaraca AVM",
        market_slug="ozkaraca-malatya",
        market_scope="city_specific",
        entrypoint_url="https://www.ozkaracaavm.com.tr/",
        evidence_url="https://www.ozkaracaavm.com.tr/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Malatya local market site lists Malatya branch, fresh grocery sections and customer service.",
    ),
    LocalMarketCandidate(
        city_slug="osmaniye",
        market_name="Yalcin Marketler Zinciri",
        market_slug="yalcin-market-osmaniye",
        market_scope="city_specific",
        entrypoint_url="https://yalcinmarket.com.tr/",
        evidence_url="https://yalcinmarket.com.tr/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Osmaniye chain site states the business started in Osmaniye and operates as a regional city market.",
    ),
    LocalMarketCandidate(
        city_slug="sakarya",
        market_name="Atilim Sanal Market",
        market_slug="atilim-sanal-market-sakarya",
        market_scope="district_cluster",
        entrypoint_url="https://www.atilimsanalmarket.com/home/",
        evidence_url="https://www.atilimsanalmarket.com/product/meysu-cola-25-l/",
        verification_status="verified",
        source_type="official_site",
        notes="Official site states it serves Sapanca and nearby districts with online grocery delivery.",
    ),
    LocalMarketCandidate(
        city_slug="sivas",
        market_name="Besler Market",
        market_slug="besler-market-sivas",
        market_scope="city_specific",
        entrypoint_url="https://apkpure.com/be%C5%9Fler-market/com.sivasbeslermarketx.mobil",
        evidence_url="https://apkpure.com/be%C5%9Fler-market/com.sivasbeslermarketx.mobil",
        verification_status="verified",
        source_type="official_app_listing",
        notes="Official app listing is published by SIVAS BESLER MARKET GIDA and provides mobile e-commerce ordering.",
    ),
    LocalMarketCandidate(
        city_slug="tokat",
        market_name="Erenler Supermarket",
        market_slug="erenler-tokat",
        market_scope="city_specific",
        entrypoint_url="https://www.erenlercep.com/",
        evidence_url="https://www.erenlercep.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Tokat local market site presents itself as a sanal market with direct ordering flow.",
    ),
    LocalMarketCandidate(
        city_slug="trabzon",
        market_name="Asya Market",
        market_slug="asya-market-trabzon",
        market_scope="city_specific",
        entrypoint_url="https://asyasanalmarket.com/",
        evidence_url="https://asyasanalmarket.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Trabzon local market chain highlights same-day delivery and Asya Sanal Market app.",
    ),
    LocalMarketCandidate(
        city_slug="van",
        market_name="Roka Market",
        market_slug="roka-market-van",
        market_scope="city_specific",
        entrypoint_url="https://www.rokamarket.com.tr/",
        evidence_url="https://www.rokamarket.com.tr/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Van local market site lists branches and states sanal market service across stores.",
    ),
    LocalMarketCandidate(
        city_slug="yalova",
        market_name="Centa AVM",
        market_slug="centa-avm-yalova",
        market_scope="city_specific",
        entrypoint_url="https://centaavm.com/",
        evidence_url="https://centaavm.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official Yalova local market site states online shopping service and lists Yalova branches.",
    ),
    LocalMarketCandidate(
        city_slug="kutahya",
        market_name="SUMA / Sultan Market",
        market_slug="suma-kutahya",
        market_scope="city_specific",
        entrypoint_url="https://www.sultanmarket.com.tr/suma",
        evidence_url="https://www.sultanmarket.com.tr/suma",
        verification_status="verified",
        source_type="official_site",
        notes="Official Kütahya-based Sultan Market site promotes SUMA as its sanal market application and ordering channel.",
    ),
    LocalMarketCandidate(
        city_slug="manisa",
        market_name="K-Depo",
        market_slug="k-depo-manisa",
        market_scope="district_cluster",
        entrypoint_url="https://k-depo.com/",
        evidence_url="https://k-depo.com/toz-urunler",
        verification_status="verified",
        source_type="official_site",
        notes="Official K-Depo online market pages list Turgutlu / Manisa contact details and active grocery-style catalog pages.",
    ),
    LocalMarketCandidate(
        city_slug="kirklareli",
        market_name="Onur Market",
        market_slug="onur-market-kirklareli",
        market_scope="city_specific",
        entrypoint_url="https://www.onurmarket.com/kirklareli",
        evidence_url="https://www.onurmarket.com/kirklareli-100yil",
        verification_status="verified",
        source_type="official_site",
        notes="Official Onur Market city/store pages show Kirklareli branches on the live online market domain with grocery categories and delivery-time UI.",
    ),
    LocalMarketCandidate(
        city_slug="tekirdag",
        market_name="Onur Market",
        market_slug="onur-market-tekirdag",
        market_scope="city_specific",
        entrypoint_url="https://www.onurmarket.com/tekirdag-koprubasi",
        evidence_url="https://www.onurmarket.com/tekirdag-100yil",
        verification_status="verified",
        source_type="official_site",
        notes="Official Onur Market Tekirdag store pages expose active grocery navigation, basket UI and branch coverage on the live ecommerce domain.",
    ),
    LocalMarketCandidate(
        city_slug="rize",
        market_name="Kale Market",
        market_slug="kale-market-rize",
        market_scope="city_specific",
        entrypoint_url="https://play.google.com/store/apps/details?id=com.kalemarketlerix.mobil",
        evidence_url="https://play.google.com/store/apps/details?id=com.kalemarketlerix.mobil",
        verification_status="verified",
        source_type="official_app_listing",
        notes="Official Google Play listing names Rize developer contact and describes Kale Online Market grocery delivery experience.",
    ),
    LocalMarketCandidate(
        city_slug="sanliurfa",
        market_name="Evdesiparis",
        market_slug="evdesiparis-sanliurfa",
        market_scope="district_cluster",
        entrypoint_url="https://evdesiparis.com/",
        evidence_url="https://evdesiparis.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official site advertises Sanliurfa / Karakopru market ordering, neighborhood delivery selection and same-day basket flow.",
    ),
    LocalMarketCandidate(
        city_slug="corum",
        market_name="Gelirr Sanal Market",
        market_slug="gelirr-corum",
        market_scope="city_specific",
        entrypoint_url="https://gelirr.com/",
        evidence_url="https://gelirr.com/p/681/fuse-tea-mango-ananas-330-ml",
        verification_status="verified",
        source_type="official_site",
        notes="Official product page shows Corum Merkez address, cart flow and live grocery pricing on the Gelirr domain.",
    ),
    LocalMarketCandidate(
        city_slug="kahramanmaras",
        market_name="Maras Market",
        market_slug="maras-market-kahramanmaras",
        market_scope="city_specific",
        entrypoint_url="https://marasmarket.com/",
        evidence_url="https://marasmarket.com/",
        verification_status="verified",
        source_type="official_site",
        notes="Official site exposes Kahramanmaras address, add-to-cart flow and T-Soft storefront structure for online ordering.",
    ),
    LocalMarketCandidate(
        city_slug="nevsehir",
        market_name="Geliver",
        market_slug="geliver-nevsehir",
        market_scope="city_specific",
        entrypoint_url="https://play.google.com/store/apps/details?id=com.geliver.app",
        evidence_url="https://play.google.com/store/apps/details?id=com.geliver.app",
        verification_status="verified",
        source_type="official_app_listing",
        notes="Official Google Play listing states grocery delivery in Nevsehir with door delivery and in-app courier tracking.",
    ),
    LocalMarketCandidate(
        city_slug="yozgat",
        market_name="Simdi Kapida / Gimat",
        market_slug="simdi-kapida-yozgat",
        market_scope="city_specific",
        entrypoint_url="https://simdikapida.com/",
        evidence_url="https://www.yozgatcamlik.com/yozgatin-sanal-marketi-acildi-gimat-marketler-zinciri-guvencesi-ile",
        verification_status="verified",
        source_type="press_and_live_domain",
        notes="Local press launch coverage and live shopping domain indicate Yozgat-focused online market activity by Gimat.",
    ),
    LocalMarketCandidate(
        city_slug="zonguldak",
        market_name="Akbal Market",
        market_slug="akbal-market-zonguldak",
        market_scope="city_specific",
        entrypoint_url="https://www.akbalmarket.com/",
        evidence_url="https://www.akbalmarket.com/contact/",
        verification_status="verified",
        source_type="official_site_plus_business_listing",
        notes="Official Magento storefront is live and third-party business listings tie the chain to Zonguldak city center and Kilimli branches.",
    ),
    LocalMarketCandidate(
        city_slug="amasya",
        market_name="Amasya Et Urunleri Market",
        market_slug="amasya-et-urunleri-market-amasya",
        market_scope="city_specific",
        entrypoint_url="https://market.amasyaeturunleri.com.tr/",
        evidence_url="https://market.amasyaeturunleri.com.tr/urun/dana-kiyma-500g/",
        verification_status="verified",
        source_type="official_site_plus_brand_reference",
        notes="Official online market exposes live product pages and delivery notes explicitly include Amasya, Merzifon and Suluova districts.",
    ),
    LocalMarketCandidate(
        city_slug="aydin",
        market_name="Bilmar Market",
        market_slug="bilmar-market-aydin",
        market_scope="district_cluster",
        entrypoint_url="https://www.bilmarmarket.com/",
        evidence_url="https://www.bilmarmarket.com/about_us",
        verification_status="verified",
        source_type="official_site",
        notes="Official about page states Bilmar launched in Aydin and serves Aydin, Efeler and Incirliova neighborhoods through its online market.",
    ),
    LocalMarketCandidate(
        city_slug="bartin",
        market_name="Marketim Bartin",
        market_slug="bartin-marketim-bartin",
        market_scope="city_specific",
        entrypoint_url="https://www.bartinmarketim.com/",
        evidence_url="https://www.bartinmarketim.com/iletisim/",
        verification_status="verified",
        source_type="official_site_plus_marketplace_reference",
        notes="Official site lists Bartin branches and directs customers to live ordering through Marul.com online market flow.",
    ),
    LocalMarketCandidate(
        city_slug="bingol",
        market_name="Bingol Market",
        market_slug="bingol-market-bingol",
        market_scope="city_specific",
        entrypoint_url="https://www.bingolmarket.com/",
        evidence_url="https://www.bingolmarket.com/pages/iletisim",
        verification_status="verified",
        source_type="official_site",
        notes="Official storefront exposes Bingol contact details, category pages and add-to-cart flow for local product commerce.",
    ),
]


def city_plate_for_slug(city_slug: str) -> int:
    return CITY_BY_SLUG[city_slug].plate_code
